import {
  MadrasaInfo,
  Leadership,
  StudentStats,
  Program,
  StaffMember,
  Facility,
  GalleryItem,
  VideoItem,
  Notice,
  EventItem,
  AdmissionInfo,
  DonationInfo,
  ContactInfo,
  SocialLink,
  SeoSettings,
  SystemSettings,
  CMSPage,
  FAQItem,
} from './types';

export const initialMadrasaInfo: MadrasaInfo = {
  name: 'Darul Uloom Siddiqia',
  arabicName: 'دار العلوم الصديقية',
  tagline: 'Rooted in Deen, Rising with Knowledge',
  taglineUrdu: 'دین میں گہری جڑیں، علم کے ساتھ سربلندی',
  taglineArabic: 'جذور في الدين، وسمو بالمعرفة',
  taglineHindi: 'दीन में जड़ें, ज्ञान के साथ प्रगति',
  establishedYear: '1998',
  registrationNo: 'DUS-ARA-BIH-0498',
  affiliatedWith: 'Waqf Educational Board & Traditional Islamic Seminary Council',
  address: 'Aurahi East, Simraha',
  city: 'Simraha',
  district: 'Araria',
  state: 'Bihar',
  country: 'India',
  pincode: '854318',
  phone: '+91 8828290721',
  whatsapp: '+91 8828290721',
  email: 'info@darululoomsiddiqia.edu',
  logoUrl: 'https://images.unsplash.com/photo-1591604466107-ec97de577aff?auto=format&fit=crop&w=400&q=80',
  bannerUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?auto=format&fit=crop&w=1600&q=80',
  description: 'Darul Uloom Siddiqia is an esteemed traditional Islamic institute founded upon authentic scholarship, prophetic character development, and holistic academic nurturing in Aurahi East, Simraha, Araria, Bihar.',
  mission: 'To preserve and impart sacred Quranic sciences, authentic Prophetic Hadith, and Islamic jurisprudence while equipping students with moral fortitude, literacy, and community leadership to benefit humanity.',
  vision: 'To nurture generations of upright Huffaz, scholars (Ulama), and conscientious citizens who combine profound spiritual wisdom with active service to nation and society.',
};

export const initialLeadership: Leadership = {
  nazimName: 'Maulana Abdus Subhan',
  nazimTitle: 'Nazim / Rector',
  designation: 'Nazim',
  biography: 'Maulana Abdus Subhan has dedicated over three decades to the propagation of classical Islamic knowledge, Quranic memorization, and educational advancement in northeastern Bihar. Under his vigilant spiritual and institutional guidance, Darul Uloom Siddiqia has flourished from a humble gathering into a revered residential educational sanctuary serving hundreds of aspiring scholars from underprivileged communities.',
  message: 'Bismillahi-r-Rahmani-r-Rahim. In the name of Allah, Most Gracious, Most Merciful. Knowledge in Islam is not merely an intellectual accumulation; it is a divine light that transforms character, anchors faith, and inspires compassion for all creation. At Darul Uloom Siddiqia, we endeavor with unwavering dedication to ensure that every student who enters our portals receives the purest classical Islamic education, memorizes the Book of Allah with meticulous Tajweed, and imbibes the noble Sunnah of our beloved Prophet Muhammad (peace be upon him). We pray Allah accepts the sincerity of our teachers, patrons, and well-wishers.',
  quote: 'Sacred knowledge without ethical practice is a vessel without water. Let our speech reflect the Quran, and let our conduct be a living proof of faith.',
  imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
  phone: '+91 8828290721',
  whatsapp: '+91 8828290721',
  email: 'nazim@darululoomsiddiqia.edu',
  officeHours: 'Monday to Thursday: 9:00 AM – 1:00 PM & 3:00 PM – 5:00 PM',
  visibility: true,
};

export const initialStudentStats: StudentStats = {
  totalStudents: 550,
  residentialStudents: 340,
  dayScholarStudents: 210,
  hifzStudents: 180,
  alimiyahStudents: 140,
  maktabStudents: 230,
  graduatedScholars: 740,
  provincesRepresented: 4,
  freeEducationPercent: 100,
  lastUpdatedYear: '2026',
};

export const initialPrograms: Program[] = [
  {
    id: 'prog-hifz',
    title: 'Hifz-ul-Quran with Meticulous Tajweed',
    titleUrdu: 'شعبہ حفظِ قرآن مع تجوید',
    titleArabic: 'قسم تحفيظ القرآن الكريم والتجويد',
    duration: '3 to 4 Years',
    eligibility: 'Ages 8 to 14 years with basic Arabic alphabet reading proficiency',
    description: 'Comprehensive memorization of the Holy Quran under certified Huffaz with strict adherence to classical rules of Tajweed, vocal rhythm, daily revision cycles, and character mentoring.',
    curriculumOverview: [
      'Nazirah (Correct articulation & phonetic precision)',
      'Memorization of 30 Juz with Daily Sabak, Sabki, and Manzil revisions',
      'Rules of Tajweed (Tuhfat al-Atfal & Al-Jazariyyah)',
      'Basic Islamic Manners (Adab & Akhlaq), Daily Masnoon Duas',
    ],
    schedule: 'Early Morning (Fajr to Ishraq), Afternoon, and Evening revision sessions',
    admissionStatus: 'open',
    feesType: 'Free / Waqf Sponsored',
    featuredImageUrl: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=800&q=80',
    order: 1,
    published: true,
  },
  {
    id: 'prog-alimiyah',
    title: 'Dars-e-Nizami (Alimiyyah Curriculum)',
    titleUrdu: 'درسِ نظامی (عالمیت کورس)',
    titleArabic: 'منهج العالمية في العلوم الإسلامية',
    duration: '6 to 7 Years',
    eligibility: 'Completed Secondary School / Maktab or equivalent religious baseline',
    description: 'The premier traditional curriculum encompassing classical Arabic morphology (Sarf), syntax (Nahw), Balaghah (Rhetoric), Fiqh (Hanafi Jurisprudence), Usul-ul-Fiqh, and Quranic Exegesis (Tafseer).',
    curriculumOverview: [
      'Classical Arabic Grammar & Literature (Nahw, Sarf, Adab)',
      'Islamic Jurisprudence & Usul (Qudoori, Hidaya, Nur al-Idah)',
      'Tafseer & Usul al-Tafseer (Jalalayn, Ma’arif al-Quran)',
      'Principles of Logic, Philosophy, and Islamic History',
    ],
    schedule: 'Full-time residential academic curriculum with daily tutorial halaqat',
    admissionStatus: 'open',
    feesType: 'Free / Waqf Sponsored',
    featuredImageUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777a?auto=format&fit=crop&w=800&q=80',
    order: 2,
    published: true,
  },
  {
    id: 'prog-dawrah',
    title: 'Dawrah-e-Hadith (Fazilat)',
    titleUrdu: 'دورۂ حدیث شریف (فضیلت)',
    titleArabic: 'دورة الحديث الشريف (الفضيلة)',
    duration: '1 Year (Capstone Specialization)',
    eligibility: 'Successful completion of 6th year Alimiyyah program',
    description: 'In-depth rigorous study of the Sihah Sittah (The Six Authentic Books of Hadith: Sahih Bukhari, Sahih Muslim, Sunan Abi Dawud, Jami al-Tirmidhi, Sunan an-Nasa’i, Sunan Ibn Majah) and Muwatta Imam Malik.',
    curriculumOverview: [
      'Comprehensive textual analysis of Sahih al-Bukhari & Sahih Muslim',
      'Hadith nomenclature (Mustalah al-Hadith) and chain validation (Isnad)',
      'Ijtihad principles, comparative fiqh, and theological consensus',
      'Comprehensive Sanad certification with authorized Ijaza',
    ],
    schedule: 'Intensive master lectures with senior Hadith scholars',
    admissionStatus: 'open',
    feesType: 'Free / Waqf Sponsored',
    featuredImageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80',
    order: 3,
    published: true,
  },
  {
    id: 'prog-maktab',
    title: 'Primary Maktab & Foundational Islamic Education',
    titleUrdu: 'ابتدائی مکتب و بنیادی تعلیم',
    titleArabic: 'المكتب التمهيدي والتعليم الأساسي',
    duration: 'Multi-level foundation',
    eligibility: 'Children aged 5 to 10 years from local and neighboring villages',
    description: 'Foundational literacy in Urdu, Hindi, English, and basic arithmetic alongside Quran recitation, basic beliefs (Aqaid), practical prayers (Salah), and moral etiquette.',
    curriculumOverview: [
      'Noorani Qaida & fluent Quranic reading',
      'Essential Islamic Creed (Aqaid-e-Islamia) & Practical Fiqh of Salah/Wudu',
      'Basic modern language literacy (Hindi, Urdu, English) and mathematics',
      'Character building, hygiene, and ethical social conduct',
    ],
    schedule: 'Morning and afternoon shifts for day scholars and boarders',
    admissionStatus: 'open',
    feesType: 'Free / Waqf Sponsored',
    featuredImageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80',
    order: 4,
    published: true,
  },
];

export const initialStaff: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'Maulana Abdus Subhan',
    nameUrdu: 'مولانا عبد السبحان',
    designation: 'Nazim & Sheikh-ul-Hadith',
    department: 'Administration & Senior Hadith Studies',
    qualification: 'Fazil-e-Dars-e-Nizami, Master of Islamic Jurisprudence & Hadith',
    biography: 'Founding Rector with over 30 years in religious education leadership, overseeing spiritual guidance and institutional administration.',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
    order: 1,
    published: true,
    contactEmail: 'nazim@darululoomsiddiqia.edu',
  },
  {
    id: 'staff-2',
    name: 'Qari Muhammad Zubair Siddiqi',
    nameUrdu: 'قاری محمد زبیر صدیقی',
    designation: 'Head of Qirat & Tajweed Department',
    department: 'Department of Quranic Memorization',
    qualification: 'Hafiz-ul-Quran, Qari Saba & Asharah (Certified Reciter)',
    biography: 'Specialist in authentic Arabic phonetics and vocal cadence with 18 years experience guiding huffaz through completion and revision.',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
    order: 2,
    published: true,
  },
  {
    id: 'staff-3',
    name: 'Maulana Tariq Anwar Nadwi',
    nameUrdu: 'مولانا طارق انور ندوی',
    designation: 'Senior Lecturer in Arabic & Islamic Jurisprudence',
    department: 'Department of Shariah & Fiqh',
    qualification: 'Alim & Fazil, Specialist in Usul al-Fiqh & Arabic Literature',
    biography: 'Teaches advanced Arabic syntax, classical jurisprudence treatises, and comparative Islamic legal frameworks.',
    imageUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=500&q=80',
    order: 3,
    published: true,
  },
  {
    id: 'staff-4',
    name: 'Maulana Masood Alam Qasmi',
    nameUrdu: 'مولانا مسعود عالم قاسمی',
    designation: 'Senior Ustadh of Hadith & Tafseer',
    department: 'Faculty of Classical Sciences',
    qualification: 'Fazilat in Hadith Studies, Specialist in Sunan Works',
    biography: 'Dedicated instructor of Sunan works and classical exegesis with deep emphasis on hadith contexts and contemporary relevance.',
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=500&q=80',
    order: 4,
    published: true,
  },
  {
    id: 'staff-5',
    name: 'Hafiz Shamsuddin Ahmad',
    nameUrdu: 'حافظ شمس الدین احمد',
    designation: 'Superintendent of Student Affairs & Dar-ul-Iqama',
    department: 'Hostel & Residential Welfare',
    qualification: 'Hafiz-ul-Quran, Diploma in Youth Counseling',
    biography: 'Oversees student discipline, residential healthcare, dining logistics, and evening revision halaqat.',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
    order: 5,
    published: true,
  },
];

export const initialFacilities: Facility[] = [
  {
    id: 'fac-masjid',
    title: 'Jamea Masjid Siddiqia',
    category: 'Spiritual',
    description: 'A spacious, serene prayer sanctuary where five daily congregate prayers, Friday sermons, and spiritual gatherings are held. Capable of accommodating over 800 worshippers.',
    capacity: '800+ Worshippers',
    features: ['Ablution (Wudu) pavilion with clean running water', 'Marble prayer hall', 'Acoustic sound system', 'Tahajjud & Itikaf quarters'],
    imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&w=800&q=80',
    order: 1,
    published: true,
  },
  {
    id: 'fac-library',
    title: 'Dar-ul-Mutala’a (Central Islamic Library)',
    category: 'Library',
    description: 'An extensive repository holding over 6,500 classical and contemporary volumes in Arabic, Urdu, Persian, Hindi, and English across Tafseer, Hadith, Fiqh, Seerah, and Islamic history.',
    capacity: '60 Reader Desks',
    features: ['Classical manuscript and rare print collections', 'Silent study alcoves', 'Reference lending counter', 'Research assistance desk'],
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    order: 2,
    published: true,
  },
  {
    id: 'fac-classrooms',
    title: 'Darsgah & Traditional Classrooms',
    category: 'Academic',
    description: 'Well-ventilated, naturally lit lecture halls and halaqah spaces designed for both traditional floor seating with low wooden desks (rihal) and modern instructional setups.',
    capacity: '14 Dedicated Classrooms',
    features: ['Traditional bookstands (rihal)', 'Audio recording facilities for major lectures', 'Chalkboards and whiteboards', 'Seasonal thermal comfort'],
    imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=800&q=80',
    order: 3,
    published: true,
  },
  {
    id: 'fac-hostel',
    title: 'Dar-ul-Iqama (Boarding & Student Residence)',
    category: 'Residential',
    description: 'Secure, clean residential boarding quarters providing free accommodation, bedding, and 24/7 adult supervisory care for over 340 outstation and orphan students.',
    capacity: '340+ Boarding Students',
    features: ['Individual student lockers and bedding', 'Round-the-clock supervisor presence', 'Sanitary shower and laundry areas', 'Dedicated sick-bay with first aid'],
    imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    order: 4,
    published: true,
  },
  {
    id: 'fac-matbakh',
    title: 'Matbakh (Community Kitchen & Dining)',
    category: 'Campus',
    description: 'Hygienic institutional kitchen preparing three wholesome, nutritious hot meals daily for all boarding students and faculty members completely free of charge.',
    capacity: '400 Meals per seating',
    features: ['Filtered potable drinking water', 'Strict hygiene and dietary standards', 'Spacious dining hall with communal dining mats', 'Daily fresh provisions'],
    imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80',
    order: 5,
    published: true,
  },
];

export const initialGallery: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Hifz-ul-Quran Halaqah at Dawn',
    description: 'Students reciting their daily lesson with devotion in the early morning stillness.',
    category: 'Students',
    imageUrl: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=1000&q=80',
    altText: 'Students engaged in Quran memorization',
    source: 'external',
    order: 1,
    published: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'gal-2',
    title: 'Annual Dastarbandi Convocation',
    description: 'Honoring newly graduated Huffaz and Ulama with traditional honorary turbans in the presence of eminent scholars.',
    category: 'Dastarbandi',
    imageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?auto=format&fit=crop&w=1000&q=80',
    altText: 'Graduation convocation at Darul Uloom Siddiqia',
    source: 'external',
    order: 2,
    published: true,
    createdAt: '2026-02-15',
  },
  {
    id: 'gal-3',
    title: 'Jamea Masjid Siddiqia Interior',
    description: 'The architectural prayer hall filled with sunlight and serenity during Zuhr congregation.',
    category: 'Masjid',
    imageUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&w=1000&q=80',
    altText: 'Sanctuary of the Jamea Masjid Siddiqia',
    source: 'external',
    order: 3,
    published: true,
    createdAt: '2026-01-20',
  },
  {
    id: 'gal-4',
    title: 'Central Classical Library Study Circle',
    description: 'Senior students consulting centuries-old Islamic commentaries for Hadith dissertation.',
    category: 'Campus',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1000&q=80',
    altText: 'Students researching in the Islamic library',
    source: 'external',
    order: 4,
    published: true,
    createdAt: '2026-01-10',
  },
  {
    id: 'gal-5',
    title: 'Primary Maktab Class in Progress',
    description: 'Young children eagerly learning the Arabic alphabet and moral values from dedicated teachers.',
    category: 'Classes',
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1000&q=80',
    altText: 'Primary Maktab students in classroom',
    source: 'external',
    order: 5,
    published: true,
    createdAt: '2025-12-18',
  },
  {
    id: 'gal-6',
    title: 'Scholarly Assembly & Community Conference',
    description: 'Visiting scholars addressing the local public on social welfare, peace, and spiritual piety.',
    category: 'Events',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1000&q=80',
    altText: 'Community gathering at Darul Uloom Siddiqia',
    source: 'external',
    order: 6,
    published: true,
    createdAt: '2025-11-25',
  },
];

export const initialVideos: VideoItem[] = [
  {
    id: 'vid-1',
    title: 'Dastarbandi Convocation & Spiritual Address by Nazim Maulana Abdus Subhan',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeVideoId: 'dQw4w9WgXcQ',
    category: 'Dastarbandi',
    description: 'Inspirational message delivered to the graduating batch of Huffaz-ul-Quran and religious scholars emphasizing service to society.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?auto=format&fit=crop&w=800&q=80',
    order: 1,
    published: true,
    createdAt: '2026-02-20',
  },
  {
    id: 'vid-2',
    title: 'Soulful Quran Recitation with Tajweed by Department Students',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeVideoId: 'dQw4w9WgXcQ',
    category: 'Tilawat',
    description: 'Mesmerizing Surah Ar-Rahman recitation showcasing precise phonetic articulation and classical maqamat.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=800&q=80',
    order: 2,
    published: true,
    createdAt: '2026-01-15',
  },
  {
    id: 'vid-3',
    title: 'Institutional Overview: Inside Darul Uloom Siddiqia Aurahi',
    youtubeUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtubeVideoId: 'dQw4w9WgXcQ',
    category: 'Campus Tour',
    description: 'A documentary walk-through of the residential hostels, dining facilities, library, and the peaceful green surroundings of Simraha, Araria.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?auto=format&fit=crop&w=800&q=80',
    order: 3,
    published: true,
    createdAt: '2025-12-10',
  },
];

export const initialNotices: Notice[] = [
  {
    id: 'not-1',
    title: 'Annual Admissions Open for Academic Session 1448–1449 AH / 2026–2027 CE',
    titleUrdu: 'تعلیمی سال کے لیے داخلہ جات کا آغاز',
    content: 'Admissions for Hifz-ul-Quran, Dars-e-Nizami (Alimiyyah), and Primary Maktab branches are now officially open. Guardians and applicants are advised to submit forms and complete the entrance assessment before the final date.',
    priority: 'urgent',
    category: 'Admission',
    publishedDate: '2026-08-15',
    expiryDate: '2026-10-30',
    externalLink: '/admission',
    linkText: 'Read Admission Guidelines',
    published: true,
  },
  {
    id: 'not-2',
    title: 'Announcement for Annual Dastarbandi Conference & Dini Ijlas',
    titleUrdu: 'سالانہ دستار بندی کانفرنس کا اعلان',
    content: 'The Annual Dastarbandi Conference celebrating this year’s graduating Huffaz and Ulama will be held on the 15th of Sha’ban on the main campus grounds. Renowned scholars from across India will grace the blessed assembly.',
    priority: 'high',
    category: 'General',
    publishedDate: '2026-08-01',
    expiryDate: '2026-11-15',
    externalLink: '/events',
    linkText: 'View Conference Details',
    published: true,
  },
  {
    id: 'not-3',
    title: 'Important Notice Regarding Mid-Term Examinations',
    titleUrdu: 'ششماہی امتحانات کا شیڈول',
    content: 'All students across Dars-e-Nizami and Tajweed sections are notified that the mid-term examinations will commence on the scheduled dates. Syllabus guidelines are available from respective department heads.',
    priority: 'normal',
    category: 'Examination',
    publishedDate: '2026-07-20',
    published: true,
  },
];

export const initialEvents: EventItem[] = [
  {
    id: 'evt-1',
    title: 'Annual Grand Dastarbandi & Khatm-e-Bukhari Assembly',
    date: '2026-10-18',
    time: '9:00 AM – 4:00 PM IST',
    location: 'Main Grounds, Darul Uloom Siddiqia, Aurahi East, Simraha, Araria',
    description: 'The monumental annual ceremony conferring turban honors upon completing Huffaz-ul-Quran and final-year Dawrah-e-Hadith scholars, followed by blessed supplications for global peace and prosperity.',
    imageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?auto=format&fit=crop&w=800&q=80',
    registrationUrl: '/contact',
    isPast: false,
    published: true,
  },
  {
    id: 'evt-2',
    title: 'Inter-Madrasa Qirat & Husn-e-Bayan Competition',
    date: '2026-11-05',
    time: '10:00 AM – 2:00 PM IST',
    location: 'Jamea Masjid Siddiqia Auditorium',
    description: 'An inspirational gathering where youth showcase their mastery over Quranic tajweed rhythms and oratorical eloquence before an esteemed panel of certified Qaris.',
    imageUrl: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?auto=format&fit=crop&w=800&q=80',
    registrationUrl: '/contact',
    isPast: false,
    published: true,
  },
  {
    id: 'evt-3',
    title: 'Seerat-un-Nabi (PBUH) Youth & Community Conference',
    date: '2026-03-12',
    time: 'After Asr Prayer till Isha',
    location: 'Central Lawn, Darul Uloom Siddiqia',
    description: 'A comprehensive educational symposium on the character, humanitarian compassion, and social wisdom of the Messenger of Allah (peace be upon him).',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80',
    isPast: true,
    published: true,
  },
];

export const initialAdmissionInfo: AdmissionInfo = {
  isOpen: true,
  academicYear: '2026–2027 (1448 AH)',
  startDate: '1st Shawwal',
  endDate: '30th Dhu al-Qadah',
  instructions: 'Darul Uloom Siddiqia welcomes deserving students regardless of their economic background. Accommodation, food, textbooks, and medical care are provided free of cost through community waqf and charitable contributions. Applicants must appear with their legal guardian for the initial verification and assessment.',
  eligibilityRequirements: [
    'For Hifz: Minimum 8 years of age with sound capability in reading the Arabic Quranic script.',
    'For Dars-e-Nizami (Alimiyat): Basic literacy in Urdu/Hindi, foundational Islamic knowledge, and successful clearing of the entrance interview.',
    'For Maktab: Minimum 5 years of age. Open to both residential boarders and day scholars.',
    'Commitment to institutional discipline, high moral conduct, and punctual attendance.',
  ],
  requiredDocuments: [
    'Birth Certificate / Proof of Date of Birth',
    'Aadhaar Card of the Student and Guardian',
    'Previous School / Madrasa Character Certificate (if applicable)',
    '4 Passport-sized Color Photographs',
    'Medical clearance confirmation certificate',
  ],
  applicationSteps: [
    { step: 1, title: 'Submission of Application', description: 'Obtain the official application form from the administrative office or download it from this portal.' },
    { step: 2, title: 'Entrance Assessment', description: 'Student attends a brief verbal reading evaluation and character conversation with the admissions committee.' },
    { step: 3, title: 'Verification & Enrollment', description: 'Verification of documents with the guardian followed by allotment of class roll and residential hostel room.' },
  ],
  contactPhone: '+91 8828290721',
  contactEmail: 'admissions@darululoomsiddiqia.edu',
  downloadableFormUrl: '#',
};

export const initialDonationInfo: DonationInfo = {
  appealTitle: 'Invest in Sacred Knowledge & the Guardians of the Quran',
  appealDescription: 'Over 340 boarding students and 210 day scholars at Darul Uloom Siddiqia receive completely free religious and moral education, lodging, meals, and books. We rely wholly upon the voluntary contributions, Zakat, Sadaqah, and Lillah of sincere believers to maintain this fortress of faith.',
  bankName: 'State Bank of India (SBI)',
  accountHolder: 'Darul Uloom Siddiqia',
  accountNumber: '39482910543',
  ifscCode: 'SBIN0003214',
  branchName: 'Simraha Branch, Araria, Bihar',
  upiId: 'darululoomsiddiqia@sbi',
  qrCodeImageUrl: 'https://images.unsplash.com/photo-1595079672139-ccd104a80083?auto=format&fit=crop&w=400&q=80',
  noteForDonors: 'Kindly indicate whether your donation is Zakat, Sadaqah, Imdad, or Lillah in the transfer narration. After making a transfer, please send a screenshot to our WhatsApp at +91 8828290721 to receive an official digital receipt.',
  taxExemptionInfo: 'Registered Non-Profit Islamic Educational Trust',
  whatsappConfirmation: '+91 8828290721',
  purposes: [
    { title: 'Sponsor a Hafiz Student', description: 'Provides complete annual food, accommodation, and educational materials for one deserving Quran student.', targetAmount: '₹ 25,000 / Year' },
    { title: 'Matbakh (Daily Food Fund)', description: 'Sponsors nutritious meals for all 340 residential students for a day or month.', targetAmount: '₹ 6,500 / Day' },
    { title: 'Hostel & Classroom Expansion', description: 'Contribution towards the ongoing construction of additional classrooms and student dormitories.', targetAmount: 'Open Sadaqah Jariyah' },
    { title: 'Library Book Endowment', description: 'Donation for acquiring classical Islamic reference volumes and encyclopedias.', targetAmount: '₹ 5,000' },
  ],
};

export const initialContactInfo: ContactInfo = {
  institutionName: 'Darul Uloom Siddiqia',
  addressLine1: 'Village Aurahi East',
  addressLine2: 'Post Office Simraha',
  village: 'Aurahi East',
  postOffice: 'Simraha',
  policeStation: 'Simraha PS',
  district: 'Araria',
  state: 'Bihar',
  country: 'India',
  pincode: '854318',
  primaryPhone: '+91 8828290721',
  secondaryPhone: '+91 8828290721',
  whatsapp: '+91 8828290721',
  email: 'info@darululoomsiddiqia.edu',
  officeHours: 'Saturday to Thursday: 8:30 AM to 1:30 PM & 3:00 PM to 5:30 PM (Closed on Friday)',
  visitingGuidelines: 'Visitors and patrons are cordially invited to witness classes and pray in the Jamea Masjid. Prior notification via WhatsApp is appreciated.',
  googleMapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d57388.94825977934!2d87.4258178877543!3d26.046399999999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39ef9be3b3b3b3b3%3A0x0!2sSimraha%2C%20Araria%2C%20Bihar!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
};

export const initialSocialLinks: SocialLink[] = [
  { id: 'soc-youtube', platform: 'youtube', label: 'YouTube Official', url: 'https://youtube.com/@darululoomsiddiqia', icon: 'fa-brands fa-youtube', order: 1, enabled: true },
  { id: 'soc-whatsapp', platform: 'whatsapp', label: 'WhatsApp Official Channel', url: 'https://wa.me/918828290721', icon: 'fa-brands fa-whatsapp', order: 2, enabled: true },
  { id: 'soc-telegram', platform: 'telegram', label: 'Telegram Broadcast', url: 'https://t.me/darululoomsiddiqia', icon: 'fa-brands fa-telegram', order: 3, enabled: true },
  { id: 'soc-instagram', platform: 'instagram', label: 'Instagram', url: 'https://instagram.com/darululoomsiddiqia', icon: 'fa-brands fa-instagram', order: 4, enabled: true },
];

export const initialSeoSettings: SeoSettings = {
  siteTitle: 'Darul Uloom Siddiqia | Aurahi East, Simraha, Araria, Bihar',
  titleTemplate: '%s | Darul Uloom Siddiqia',
  defaultDescription: 'Official website of Darul Uloom Siddiqia in Aurahi East, Simraha, Araria, Bihar, India. Led by Nazim Maulana Abdus Subhan. Dedicated to Hifz-ul-Quran, Dars-e-Nizami, and authentic Islamic scholarship.',
  keywords: [
    'Darul Uloom Siddiqia',
    'Darul Uloom Siddiqia Aurahi',
    'Darul Uloom Siddiqia Aurahi East',
    'Darul Uloom Siddiqia Aurahi West',
    'Darul Uloom Siddiqia Simraha',
    'Darul Uloom Siddiqia Araria',
    'Darul Uloom Siddiqia Bihar',
    'Darul Uloom Siddiqia India',
    'Darul Uloom Siddiqia Abdus Subhan',
    'Maulana Abdus Subhan',
    'Nazim Darul Uloom Siddiqia',
    'Islamic Seminary Bihar',
    'Madrasa Araria',
    'Hifz ul Quran Bihar',
  ],
  canonicalBaseUrl: 'https://darululoomsiddiqia.edu',
  ogImageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?auto=format&fit=crop&w=1200&q=80',
  twitterHandle: '@DUSiddiqia',
  organizationSchema: {
    name: 'Darul Uloom Siddiqia',
    url: 'https://darululoomsiddiqia.edu',
    logo: 'https://images.unsplash.com/photo-1591604466107-ec97de577aff?auto=format&fit=crop&w=400&q=80',
    foundingDate: '1998',
    founder: 'Maulana Abdus Subhan',
    addressCountry: 'India',
  },
};

export const initialSystemSettings: SystemSettings = {
  defaultLanguage: 'en',
  enableMultiLanguage: true,
  maintenanceMode: false,
  announcementTicker: 'Admissions Open for 2026–2027 Academic Session • Annual Dastarbandi Conference Scheduled for 15th Sha’ban • Direct WhatsApp Hotline: +91 8828290721',
  enableTicker: true,
  lastBackupDate: new Date().toISOString(),
};

export const initialPages: CMSPage[] = [
  {
    id: 'page-home',
    title: 'Home',
    slug: 'home',
    description: 'Welcome to Darul Uloom Siddiqia, an Islamic center of learning and spiritual excellence in Aurahi East, Simraha, Araria, Bihar.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?auto=format&fit=crop&w=1600&q=80',
    isInNavigation: true,
    navLabel: 'Home',
    order: 1,
    status: 'published',
    seoTitle: 'Darul Uloom Siddiqia - Rooted in Deen, Rising with Knowledge',
    seoDescription: 'Official portal of Darul Uloom Siddiqia, Aurahi East, Simraha, Araria, Bihar. Founded under the leadership of Nazim Maulana Abdus Subhan.',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-10',
    sections: [
      {
        id: 'sec-hero-1',
        type: 'hero',
        title: 'Rooted in Deen, Rising with Knowledge',
        subtitle: 'DARUL ULOOM SIDDIQIA • AURAHI EAST, SIMRAHA, ARARIA, BIHAR',
        description: 'An illustrious sanctuary of authentic Quranic sciences, prophetic Sunnah, and classical Islamic scholarship nurturing upright Huffaz, scholars, and servants of humanity.',
        imageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?auto=format&fit=crop&w=1600&q=80',
        imageAlt: 'Darul Uloom Siddiqia campus and prayer assembly',
        ctaText: 'Explore Academic Programs',
        ctaUrl: '/education',
        secondaryCtaText: 'Support & Donate',
        secondaryCtaUrl: '/donation',
        backgroundColor: 'emerald',
        order: 1,
        published: true,
      },
      {
        id: 'sec-stats-1',
        type: 'statistics',
        title: 'Institutional Pillars at a Glance',
        subtitle: 'Our Growth & Impact in Bihar and Beyond',
        description: 'Guided by the visionary stewardship of Nazim Maulana Abdus Subhan, providing 100% waqf-sponsored education.',
        backgroundColor: 'ivory',
        order: 2,
        published: true,
        items: [
          { id: 'st-1', title: '550+', subtitle: 'Total Active Students', description: 'Residential boarders & local day scholars', icon: 'fa-solid fa-graduation-cap' },
          { id: 'st-2', title: '340+', subtitle: 'Residential Boarders', description: 'Provided complete free lodging & meals', icon: 'fa-solid fa-bed' },
          { id: 'st-3', title: '740+', subtitle: 'Graduated Huffaz & Ulama', description: 'Serving communities worldwide', icon: 'fa-solid fa-book-quran' },
          { id: 'st-4', title: '100%', subtitle: 'Free / Waqf Sponsored', description: 'Zero financial burden on student families', icon: 'fa-solid fa-hand-holding-heart' },
        ],
      },
      {
        id: 'sec-lead-1',
        type: 'quote',
        title: 'Message from the Nazim',
        subtitle: 'MAULANA ABDUS SUBHAN • NAZIM, DARUL ULOOM SIDDIQIA',
        description: 'Knowledge in Islam is a divine light that transforms character, anchors faith, and inspires compassion for all creation. We endeavor with unwavering sincerity to ensure every student memorizes the Book of Allah and imbibes the noble Sunnah.',
        imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
        imageAlt: 'Maulana Abdus Subhan, Nazim of Darul Uloom Siddiqia',
        ctaText: 'Read Full Message & Biography',
        ctaUrl: '/nazim',
        backgroundColor: 'default',
        order: 3,
        published: true,
      },
      {
        id: 'sec-features-1',
        type: 'features',
        title: 'Pillars of Siddiqia Education',
        subtitle: 'Nurturing Intellect, Spirit, and Character',
        backgroundColor: 'ivory',
        order: 4,
        published: true,
        items: [
          { id: 'f-1', title: 'Authentic Sanad & Isnad', description: 'Continuous chain of transmission connecting students directly to the Prophet Muhammad (peace be upon him).', icon: 'fa-solid fa-scroll' },
          { id: 'f-2', title: 'Meticulous Tajweed', description: 'Certified mastery in phonetic articulation under veteran Qaris of recognized authority.', icon: 'fa-solid fa-book-open' },
          { id: 'f-3', title: 'Holistic Boarding Care', description: 'Nutritious meals, sanitary living quarters, and continuous moral mentoring in an environment of serenity.', icon: 'fa-solid fa-shield-heart' },
          { id: 'f-4', title: 'Community & National Service', description: 'Instilling humanitarian empathy, communal harmony, and active civic responsibility.', icon: 'fa-solid fa-hands-holding-child' },
        ],
      },
      {
        id: 'sec-cta-1',
        type: 'cta',
        title: 'Join in Safeguarding Sacred Knowledge',
        subtitle: 'Sadaqah Jariyah for Here and the Hereafter',
        description: 'Your contribution sustains the daily nourishment, education, and boarding of hundreds of young memorizers of the Holy Quran.',
        ctaText: 'Donate via UPI / Bank',
        ctaUrl: '/donation',
        secondaryCtaText: 'Contact Office on WhatsApp',
        secondaryCtaUrl: 'https://wa.me/918828290721',
        backgroundColor: 'emerald',
        order: 5,
        published: true,
      },
    ],
  },
  {
    id: 'page-about',
    title: 'About',
    slug: 'about',
    description: 'History, spiritual foundations, and academic lineage of Darul Uloom Siddiqia in Simraha, Araria.',
    featuredImageUrl: 'https://images.unsplash.com/photo-1591604466107-ec97de577aff?auto=format&fit=crop&w=1200&q=80',
    isInNavigation: true,
    navLabel: 'About',
    order: 2,
    status: 'published',
    seoTitle: 'About Darul Uloom Siddiqia - Simraha, Araria, Bihar',
    seoDescription: 'Discover the noble origins, philosophy, and mission of Darul Uloom Siddiqia located in Aurahi East, Araria, Bihar.',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
    sections: [
      {
        id: 'sec-ab-hero',
        type: 'hero',
        title: 'Dedicated to Prophetic Wisdom & Character',
        subtitle: 'OUR SACRED TRUST & FOUNDATIONAL STORY',
        description: 'Darul Uloom Siddiqia was established with the noble intention of serving as a fortress of classical Islamic learning and social rectitude in northeastern Bihar.',
        imageUrl: 'https://images.unsplash.com/photo-1591604466107-ec97de577aff?auto=format&fit=crop&w=1200&q=80',
        backgroundColor: 'emerald',
        order: 1,
        published: true,
      },
      {
        id: 'sec-ab-text',
        type: 'rich_text',
        title: 'Our History & Mission',
        subtitle: 'From Modest Beginnings to a Revered Institution',
        contentHtml: `<p class="lead text-lg text-emerald-950 font-medium mb-4">Founded in 1998 in the rural expanse of Aurahi East, Simraha, Araria, Darul Uloom Siddiqia emerged to address the profound scarcity of classical Islamic educational infrastructure in the region.</p><p class="mb-4 text-gray-700">Under the visionary and untiring leadership of Nazim Maulana Abdus Subhan, the institution has nurtured thousands of young minds from impoverished agrarian families, offering them world-class religious instruction, boarding, and sustenance without any financial burden.</p><p class="text-gray-700">Our institution operates under the classical Dars-e-Nizami framework while proactively integrating essential contemporary literacy, encouraging moral uprightness, and instilling profound respect for human dignity and nationhood.</p>`,
        backgroundColor: 'default',
        order: 2,
        published: true,
      },
    ],
  },
  {
    id: 'page-nazim',
    title: 'Nazim / Leadership',
    slug: 'nazim',
    description: 'Profile, message, and guidance from Nazim Maulana Abdus Subhan.',
    isInNavigation: true,
    navLabel: 'Leadership',
    order: 3,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-education',
    title: 'Education',
    slug: 'education',
    description: 'Academic departments, curriculum overview, and pedagogical methodology.',
    isInNavigation: true,
    navLabel: 'Education',
    order: 4,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-students',
    title: 'Students',
    slug: 'students',
    description: 'Student life, aggregate demographics, and daily routine at Darul Uloom Siddiqia.',
    isInNavigation: true,
    navLabel: 'Students',
    order: 5,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-staff',
    title: 'Teachers & Staff',
    slug: 'staff',
    description: 'Distinguished faculty of Ulama, certified Huffaz, and administrative personnel.',
    isInNavigation: true,
    navLabel: 'Staff',
    order: 6,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-facilities',
    title: 'Campus & Facilities',
    slug: 'facilities',
    description: 'The physical campus including Jamea Masjid, library, boarding hostel, and dining quarters.',
    isInNavigation: true,
    navLabel: 'Facilities',
    order: 7,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-gallery',
    title: 'Gallery',
    slug: 'gallery',
    description: 'Visual chronicles of campus life, convocations, and spiritual assemblies.',
    isInNavigation: true,
    navLabel: 'Gallery',
    order: 8,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-videos',
    title: 'Videos & Media',
    slug: 'videos',
    description: 'Lectures, speeches, Quranic recitations, and documentary glimpses.',
    isInNavigation: true,
    navLabel: 'Videos',
    order: 9,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-notices',
    title: 'Notices',
    slug: 'notices',
    description: 'Official circulars, exam dates, and institutional announcements.',
    isInNavigation: true,
    navLabel: 'Notices',
    order: 10,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-events',
    title: 'Events',
    slug: 'events',
    description: 'Upcoming and past academic conferences, convocations, and assemblies.',
    isInNavigation: true,
    navLabel: 'Events',
    order: 11,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-admission',
    title: 'Admission',
    slug: 'admission',
    description: 'Application procedures, criteria, and guidelines for prospective students.',
    isInNavigation: true,
    navLabel: 'Admission',
    order: 12,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-donation',
    title: 'Donation',
    slug: 'donation',
    description: 'Official bank details, UPI ID, and QR code to contribute Zakat and Sadaqah.',
    isInNavigation: true,
    navLabel: 'Donation',
    order: 13,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-faq',
    title: 'FAQ',
    slug: 'faq',
    description: 'Frequently asked questions regarding studies, boarding, and visits.',
    isInNavigation: true,
    navLabel: 'FAQ',
    order: 14,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
  {
    id: 'page-contact',
    title: 'Contact',
    slug: 'contact',
    description: 'Address, phone, WhatsApp (+91 8828290721), and visiting directions.',
    isInNavigation: true,
    navLabel: 'Contact',
    order: 15,
    status: 'published',
    isSystemPage: true,
    createdAt: '2026-01-01',
    updatedAt: '2026-03-01',
  },
];

export const initialFaqList: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How can a student apply for admission at Darul Uloom Siddiqia?',
    questionUrdu: 'دارالعلوم صدیقیہ میں داخلے کے لیے کیسے درخواست دیں؟',
    answer: 'Admissions open annually in the month of Shawwal. Guardians should visit the administrative office with the student, their Aadhaar card, birth certificate, and previous academic records. A reading test and brief interview determine placement.',
    category: 'Admission',
    order: 1,
    published: true,
  },
  {
    id: 'faq-2',
    question: 'What are the charges or fees for boarding, food, and tuition?',
    questionUrdu: 'کیا قیام، طعام اور تعلیم کی کوئی فیس ہے؟',
    answer: 'Darul Uloom Siddiqia provides completely free tuition, residential lodging, nutritious food, and essential textbooks to all enrolled students, funded through community waqf, Zakat, and voluntary donations.',
    category: 'General',
    order: 2,
    published: true,
  },
  {
    id: 'faq-3',
    question: 'What academic curricula are taught?',
    questionUrdu: 'یہاں کون سے نصاب پڑھائے جاتے ہیں؟',
    answer: 'We offer full-time Hifz-ul-Quran with Tajweed, the comprehensive Dars-e-Nizami (Alimiyyah degree), along with foundational Arabic, Urdu, Hindi, English, and basic mathematics.',
    category: 'Academic',
    order: 3,
    published: true,
  },
  {
    id: 'faq-4',
    question: 'How can donors contribute or sponsor a student?',
    questionUrdu: 'عطیات اور تعاون کیسے کیا جا سکتا ہے؟',
    answer: 'Donations can be transferred directly to the official Madrasa State Bank of India account or via UPI (darululoomsiddiqia@sbi). You can sponsor a Hafiz student, contribute to the daily Matbakh (kitchen), or donate towards construction.',
    category: 'Donation',
    order: 4,
    published: true,
  },
  {
    id: 'faq-5',
    question: 'Where is the institution located and what are visiting guidelines?',
    questionUrdu: 'ادارہ کہاں واقع ہے اور ملاقات کا طریقہ کار کیا ہے؟',
    answer: 'The campus is located in Aurahi East, Post Simraha, District Araria, Bihar, India (PIN 854318). Guests and patrons are welcome Saturday through Thursday between 8:30 AM and 5:30 PM.',
    category: 'General',
    order: 5,
    published: true,
  },
];
